name: Build Vue
on: [ push ]
jobs:
  build_vue:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - env:
          VITE_API_TOKEN: ${{ secrets.VITE_API_TOKEN }}
        uses: actions/checkout@v3
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Sanchoys21'
          reponame: 'test'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
